"""add oauth 2.0 + make provisions on DB

Revision ID: 4aa0a54f0af5
Revises: 5c33f3a1a511
Create Date: 2026-06-30 20:12:07.402910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4aa0a54f0af5"
down_revision: Union[str, Sequence[str], None] = "5c33f3a1a511"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add provider with a temporary default for existing users
    op.add_column(
        "user",
        sa.Column(
            "provider",
            sa.String(length=255),
            nullable=False,
            server_default="local",
        ),
    )

    # Add provider_id
    op.add_column(
        "user",
        sa.Column(
            "provider_id",
            sa.String(),
            nullable=True,
        ),
    )

    # OAuth users won't have a password
    op.alter_column(
        "user",
        "password_hash",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )

    # Remove the default so new rows must explicitly specify a provider
    op.alter_column(
        "user",
        "provider",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password_hash", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("user", "provider_id")
    op.drop_column("user", "provider")
    # ### end Alembic commands ###
