"""add capsule table

Revision ID: 5c33f3a1a511
Revises: 
Create Date: 2026-06-30 19:42:19.973978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c33f3a1a511'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsule', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('capsule', sa.Column('subject', sa.String(length=255), nullable=False))
    op.add_column('capsule', sa.Column('body', sa.String(), nullable=True))
    op.add_column('capsule', sa.Column('del_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('capsule', sa.Column('api_ver', sa.String(), nullable=False))
    op.add_column('capsule', sa.Column('client_ip', postgresql.INET(), nullable=False))
    op.add_column('capsule', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('capsule', sa.Column('updated_at', sa.Time(timezone=True), nullable=False))
    op.add_column('capsule', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('capsule', sa.Column('email_list', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_capsule_api_ver'), 'capsule', ['api_ver'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capsule_api_ver'), table_name='capsule')
    op.drop_column('capsule', 'email_list')
    op.drop_column('capsule', 'status')
    op.drop_column('capsule', 'updated_at')
    op.drop_column('capsule', 'created_at')
    op.drop_column('capsule', 'client_ip')
    op.drop_column('capsule', 'api_ver')
    op.drop_column('capsule', 'del_time')
    op.drop_column('capsule', 'body')
    op.drop_column('capsule', 'subject')
    op.drop_column('capsule', 'user_id')
    # ### end Alembic commands ###
