"""Update refresh token expiry

Revision ID: ea74d49d8b8c
Revises: 4aa0a54f0af5
Create Date: 2026-07-01 17:49:22.618330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea74d49d8b8c'
down_revision: Union[str, Sequence[str], None] = '4aa0a54f0af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
