"""drop_unique_api_ver_v2

Revision ID: 463ee4651829
Revises: 6a1e861ad81d
Create Date: 2026-07-03 14:16:24.416876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463ee4651829'
down_revision: Union[str, Sequence[str], None] = '6a1e861ad81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capsule_api_ver'), table_name='capsule')
    op.create_index(op.f('ix_capsule_api_ver'), 'capsule', ['api_ver'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capsule_api_ver'), table_name='capsule')
    op.create_index(op.f('ix_capsule_api_ver'), 'capsule', ['api_ver'], unique=True)
    # ### end Alembic commands ###
