"""fix updated_at to datetime

Revision ID: a936fa66db1e
Revises: 24d4daba3758
Create Date: 2026-07-02 23:14:26.539891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a936fa66db1e"
down_revision: Union[str, Sequence[str], None] = "24d4daba3758"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "capsule",
        "updated_at",
        existing_type=postgresql.TIME(timezone=True),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        postgresql_using="CURRENT_DATE + updated_at",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "capsule",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIME(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
