"""add version to capsule

Revision ID: bf4a880b2191
Revises: 463ee4651829
Create Date: 2026-07-05 19:35:27.249247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bf4a880b2191"
down_revision: Union[str, Sequence[str], None] = "463ee4651829"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "capsule",
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.alter_column("capsule", "version", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("capsule", "version")
    # ### end Alembic commands ###
