"""fix token_version type

Revision ID: f3b4c7a4e462
Revises: ea74d49d8b8c
Create Date: 2026-07-02 17:57:58.356349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f3b4c7a4e462"
down_revision: Union[str, Sequence[str], None] = "ea74d49d8b8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_token",
        sa.Column("token_version", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_token", "token_version")
    # ### end Alembic commands ###
