"""add attachments column to capsule

Revision ID: f829ef0d1b5c
Revises: bf4a880b2191
Create Date: 2026-07-05 20:26:59.851855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f829ef0d1b5c'
down_revision: Union[str, Sequence[str], None] = 'bf4a880b2191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsule', sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capsule', 'attachments')
    # ### end Alembic commands ###
